#!/bin/bash

# 8ball answers any question with a random answer like the magic eight
# ball toy. If any argument is passed it assumes the combined arguments
# are the question, otherwise, it waits and prompts the user to type in
# a question and will continue to wait and prompt for subsequent
# questions providing essential life advice.

black=$'\e[30m'
red=$'\e[31m'
green=$'\e[32m'
yellow=$'\e[33m'
blue=$'\e[34m'
magenta=$'\e[35m'
cyan=$'\e[36m'
white=$'\e[37m'
reset=$'\e[0m'


declare art=$blue'
        ____
    ,dP9CGG88@b,
  ,IP  _   Y888@@b,
 dIi  (_)   G8888@b
dCII  (_)   G8888@@b
GCCIi     ,GG8888@@@
GGCCCCCCCGGG88888@@@
GGGGCCCGGGG88888@@@@...
Y8GGGGGG8888888@@@@P.....
 Y88888888888@@@@@P......
  Y8888888@@@@@@@P......
    @@@@@@@@@@PP .......
       """""........
'$reset

declare dir="${0%%/*}"
readarray -t answers < "${dir:-.}/answers.txt"

# declare -a answers=(
#    'It is certain'
# 	 'Reply hazy, try again'
# 	 'Don’t count on it'
#    'It is decidedly so'
# 	 'Ask again later'
# 	 'My reply is no'
#    'Without a doubt'
# 	 'Better not tell you now'
# 	 'My sources say no'
#    'Yes definitely'
# 	 'Cannot predict now'
# 	 'Outlook not so good'
#    'You may rely on it'
# 	 'Concentrate and ask again'
# 	 'Very doubtful'
#    'As I see it, yes'
#    'Most likely'
#    'Outlook good'
#    'Yes'
#    'Signs point to yes'
# )

welcome ()
{
	echo "$art"
  echo "$red"
  cat <<-EOM
	🎱 Welcome to the magic eight ball. Enter a yes or no question and
	your answer will be granted.
	EOM
  echo "$reset"
}

8ball ()
{
	local $i 
	welcome
	while IFS= read -p "> " line; do
    printf "${magenta}Q${reset}: %s\n" "$line"
		printf "${blue}A${reset}: %s\n"  "${answers[RANDOM%${#answers}]}"

# TODO using match logic comparisons, if statement and RANDOM create
# random yes, no, maybe answer (no arrays yet)
#		i=$((RANDOM % 3))

# 		((i==0)) && echo "Yes. 🎱" && continue
# 		((i==1)) && echo "No. 🎱" && continue
# 		((i==2)) && echo "Maybe. 🎱" && continue
# 		echo "Randomization error."

# 		if ((i==0)); then
# 			printf "Yes. 🎱"
# 		elif ((i==1)); then
# 			printf "No. 🎱"
# 		elif ((i==2)); then
# 			printf "Maybe. 🎱"
# 		else
# 			printf "Randomization error."
# 		fi

#     case "$i" in
# 		0) printf "Yes. 🎱" ;;
# 		1) printf "No. 🎱" ;;
# 		2) printf "Maybe. 🎱" ;;
# 		*) printf "What/" ;;
# 		esac
	done
}

8ball
