#!/bin/bash

# f(x) = 2(x) + 1
# y = 2(x) + 1
# y = 2(x) + 1
# ((y = (2*x) + 1))
# add(x,y) 
# y = add( 2(x), 1 )
# y = add( first, second )
# y = add( height, width )
# y = add(34,2)
# y = add(2,324)

name="Rob Muhlestein"
printf "Hello there, %s. Today is %s\n" "$name" "$(date)"

