#!/usr/bin/env bash

if test -t 1; then
  BLACK=$'\e[30m'
  RED=$'\e[31m'
  RESET=$'\e[0m'
  CLEAR=$'\e[H\e[2J'
fi

printf "${BLACK}black=$'\\\\e[30m'\n$RESET"
printf "${RED}red=$'\\\\e[31m'\n$RESET"

